title: Jonathan Abeje CEAMLS SAIRI Website Summer 2024
logo: assets/img/IMG_6974.jpg
description: |
  Hi! My name is Jonathan Abeje and this is my CEAMLS SAIRI Website for Summer 2024. 
  [View My LinkedIn Profile](https://www.linkedin.com/in/jonathan-abeje/)  
  [View My GitHub Profile](https://github.com/joniabeje)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
